mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.'polls.views.home'', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^polls/', include('polls.urls', namespace="polls")),
    #url(r'^admin/', include(admin.site.urls)),
      url(r'^$', 'polls.views.IndexView', name='index'),
                       url(r'^(?P<poll_id>\d+)/$', 'polls.views.DetailsView', name='detail'), #view details

                       url(r'^(?P<poll_id>\d+)/vote/$', 'polls.views.vote', name='vote'), #process vote
                       url(r'^login$', 'polls.views.login_view', name='login'), # process login
                       url(r'^logout$', 'polls.views.logout_view', name='logout'), # process logout
                       url(r'^signup$', 'polls.views.signup', name='signup'), # process signup
                       url(r'^register$', 'polls.views.register', name='register'), # register account
                       url(r'^create$', 'polls.views.create', name='create'), # create a poll
                       url(r'^account$', 'polls.views.account', name='account'), # view account
                       url(r'^comment$', 'polls.views.comment', name='comment'), # create comment
                       url(r'^directory$', 'polls.views.directory', name='directory'), # view directory of tags
                       url(r'^search$', 'polls.views.search', name='search'), # search polls/tags
                       url(r'^(?P<poll_id>\d+)/delete/$', 'polls.views.delete', name='delete'), #process vote



)

pollnation/urls.py
from django.conf.urls import patterns, include, url
from polls import views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.'polls.views.home'', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^polls/', include('polls.urls', namespace="polls")),
    #url(r'^admin/', include(admin.site.urls)),
      url(r'^$', 'polls.views.IndexView', name='index'),
                       url(r'^(?P<poll_id>\d+)/$', 'polls.views.DetailsView', name='detail'), #view details

                       url(r'^(?P<poll_id>\d+)/vote/$', 'polls.views.vote', name='vote'), #process vote
                       url(r'^login$', 'polls.views.login_view', name='login'), # process login
                       url(r'^logout$', 'polls.views.logout_view', name='logout'), # process logout
                       url(r'^signup$', 'polls.views.signup', name='signup'), # process signup
                       url(r'^register$', 'polls.views.register', name='register'), # register account
                       url(r'^create$', 'polls.views.create', name='create'), # create a poll
                       url(r'^account$', 'polls.views.account', name='account'), # view account
                       url(r'^comment$', 'polls.views.comment', name='comment'), # create comment
                       url(r'^directory$', 'polls.views.directory', name='directory'), # view directory of tags
                       url(r'^search$', 'polls.views.search', name='search'), # search polls/tags
                       url(r'^(?P<poll_id>\d+)/delete/$', 'polls.views.delete', name='delete'), #process vote



)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views


urlpatterns = patterns('',
                       url(r'^$', views.IndexView, name='index'),
                       url(r'^(?P<poll_id>\d+)/$', views.DetailsView, name='detail'), #view details

                       url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'), #process vote
                       url(r'^login$', views.login_view, name='login'), # process login
                       url(r'^logout$', views.logout_view, name='logout'), # process logout
                       url(r'^signup$', views.signup, name='signup'), # process signup
                       url(r'^register$', views.register, name='register'), # register account
                       url(r'^create$', views.create, name='create'), # create a poll
                       url(r'^account$', views.account, name='account'), # view account
                       url(r'^comment$', views.comment, name='comment'), # create comment
                       url(r'^directory$', views.directory, name='directory'), # view directory of tags
                       url(r'^search$', views.search, name='search'), # search polls/tags
                       url(r'^(?P<poll_id>\d+)/delete/$', views.delete, name='delete'), #process vote

)

polls/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
import hashlib
# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User)

    def gravatar_url(self):
        return "http://www.gravatar.com/avatar/%s?s=50" % hashlib.md5(self.user.email).hexdigest()


User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    creator = models.ForeignKey(User, null=True)
    tags = TaggableManager()

    def __unicode__(self):
        return self.question

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text


class Comment(models.Model):
    poll = models.ForeignKey(Poll)
    user = models.ForeignKey(User)
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_text = models.TextField(max_length=500)

    def __unicode__(self):
        return self.current_text


class Vote(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.ForeignKey(Choice)
    ip = models.GenericIPAddressField()
    date = models.DateTimeField('date voted',auto_now_add=True)
   

polls/views.py
# Create your views here.
import re

from operator import attrgetter
from itertools import chain

from django.utils import timezone
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.contrib.auth import login, authenticate, logout
from django.db.models import Sum
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.forms.formsets import formset_factory, BaseFormSet

from polls.models import Choice, Poll
from polls.forms import AuthenticateForm, UserCreateForm, CommentForm, PollForm, ChoiceForm


def IndexView(request):
    poll_list = Poll.objects.annotate(num_votes=Sum('choice__votes')).filter(pub_date__lte=timezone.now()).order_by(
        '-pub_date')
    paginator = Paginator(poll_list, 5) # Show 5 polls per page

    # Make sure page request is an int. If not, deliver first page.
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    # If page request (9999) is out of range, deliver last page of results.
    try:
        polls = paginator.page(page)
    except (EmptyPage, InvalidPage):
        polls = paginator.page(paginator.num_pages)

    if request.user.is_authenticated():
        auth_form = False
        logged_in = True

    else:
        logged_in = False
        auth_form = AuthenticateForm()

    top_polls = Poll.objects.annotate(num_votes=Sum('choice__votes')).order_by('-num_votes')
    top_tags = Poll.tags.most_common()[:10]

    return render_to_response('polls/index.html',
                              {"polls": polls, "top_polls": top_polls, "top_tags": top_tags, "auth_form": auth_form,
                               "logged_in": logged_in}, context_instance=RequestContext(request))


def DetailsView(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    top_polls = Poll.objects.annotate(num_votes=Sum('choice__votes')).order_by('-num_votes')
    top_tags = Poll.tags.most_common()[:10]
    similar_polls = poll.tags.similar_objects()[:5]
    comment_form = CommentForm()
    if request.user.is_authenticated():
        auth_form = False
        logged_in = True

    else:
        logged_in = False
        auth_form = AuthenticateForm()
    return render_to_response('polls/detail.html',
                              {"poll": poll, "top_polls": top_polls, "top_tags": top_tags, "auth_form": auth_form,
                               "logged_in": logged_in, "comment_form": comment_form, "similar_polls": similar_polls},
                              context_instance=RequestContext(request))


def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        top_polls = Poll.objects.annotate(num_votes=Sum('choice__votes')).order_by('-num_votes')
        top_tags = Poll.tags.most_common()[:10]
        if request.user.is_authenticated():
            auth_form = False
            logged_in = True

        else:
            logged_in = False
            auth_form = AuthenticateForm()
        return render(request, 'polls/detail.html',
                      {'poll': p, 'error_message': "You didn't select a choice.", "top_polls": top_polls,
                       "top_tags": top_tags, "auth_form": auth_form,
                       "logged_in": logged_in}, context_instance=RequestContext(request))
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:detail', args=(p.id,)))


def login_view(request):
    if request.method == 'POST':
        form = AuthenticateForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            # Success
            return redirect('/polls')
        else:
            # Failure
            return IndexView(request)
    return redirect('/polls')


def logout_view(request):
    logout(request)
    return redirect('/polls')


def signup(request):
    user_form = UserCreateForm(data=request.POST)
    if request.method == 'POST':
        if user_form.is_valid():
            username = user_form.clean_username()
            password = user_form.clean_password2()
            user_form.save()
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/polls')
        else:
            return register(request, user_form=user_form)
    return redirect('/polls/register')



def comment(request):
    user_comment = CommentForm(data=request.POST)
    if request.method == 'POST':
        if user_comment.is_valid():
            comment = user_comment.save(commit=False)
            comment.user = request.user
            poll = Poll.objects.get(pk=request.POST['pollid'])
            comment.poll = poll
            comment.save()
            return DetailsView(request,request.POST['pollid'])
        else:
            return DetailsView(request,request.POST['pollid'])
    return redirect(request.path)


def register(request, user_form="none"):
    if user_form == "none":
        user_form = UserCreateForm()

    return render(request, 'polls/register.html', {
        'user_form': user_form,
    })


def directory(request):
    top_polls = Poll.objects.annotate(num_votes=Sum('choice__votes')).order_by('-num_votes')
    top_tags = Poll.tags.most_common()[:10]
    all_tags = Poll.tags.most_common()
    if request.user.is_authenticated():
        auth_form = False
        logged_in = True

    else:
        logged_in = False
        auth_form = AuthenticateForm()
    return render_to_response('polls/directory.html',
                              {"top_polls": top_polls, "top_tags": top_tags, "auth_form": auth_form,
                               "logged_in": logged_in, "all_tags": all_tags}, context_instance=RequestContext(request))


def search(request):
    query_string = ''
    found_entries = None
    
    top_polls = Poll.objects.annotate(num_votes=Sum('choice__votes')).order_by('-num_votes')
    top_tags = Poll.tags.most_common()[:10]
    
    if request.user.is_authenticated():
            auth_form = False
            logged_in = True

    else:
        logged_in = False
        auth_form = AuthenticateForm()

    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']

        entry_query = get_query(query_string, ['question'])

        tag_query = normalize_query(query_string)
        found_entries = Poll.objects.annotate(num_votes=Sum('choice__votes')).filter(entry_query).order_by('-pub_date').distinct()
        tag_entries = Poll.objects.filter(tags__name__in=tag_query).distinct()

        
        result_list = found_entries | tag_entries

        paginator = Paginator(result_list, 5) # Show 5 polls per page

        # Make sure page request is an int. If not, deliver first page.
        try:
            page = int(request.GET.get('page', '1'))
        except ValueError:
            page = 1

        # If page request (9999) is out of range, deliver last page of results.
        try:
            polls = paginator.page(page)
        except (EmptyPage, InvalidPage):
            polls = paginator.page(paginator.num_pages)

        

        

        return render_to_response('polls/search_results.html',
                                  {"top_polls": top_polls, "top_tags": top_tags, "auth_form": auth_form, "polls": polls,
                                   "logged_in": logged_in, 'query_string': query_string, 'result_list': result_list},
                                  context_instance=RequestContext(request))
    else:
        result_list = False
        return render_to_response('polls/search_results.html',
                              {"top_polls": top_polls, "top_tags": top_tags, "auth_form": auth_form,
                               "logged_in": logged_in, 'query_string': query_string, 'result_list': result_list},
                              context_instance=RequestContext(request))


def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]


def get_query(query_string, search_fields):
    query = None # Query to search for every search term
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query | or_query
    return query

def create(request):
    
    class RequiredFormSet(BaseFormSet):
        def __init__(self, *args, **kwargs):
            super(RequiredFormSet, self).__init__(*args, **kwargs)
            for form in self.forms:
                form.empty_permitted = False

    ChoiceFormSet = formset_factory(ChoiceForm, max_num=10, formset=RequiredFormSet)
    if request.method == 'POST': # If the form has been submitted...
        poll_form = PollForm(request.POST) # A form bound to the POST data
        # Create a formset from the submitted data
        choice_formset = ChoiceFormSet(request.POST, request.FILES)

        if poll_form.is_valid() and choice_formset.is_valid():
            poll = poll_form.save(commit=False)
            if request.user.is_authenticated():
                poll.creator = request.user
            poll.save()
            poll_form.save_m2m()

polls/templates/polls/base.html
<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>Pollnation</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'polls/images/favicon.png' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/prettyPhoto.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/type/classic.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/type/goudy.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/jquery.jqplot.min.css' %}"/>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'polls/js/jquery.jqplot.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'polls/js/jqplot.pieRenderer.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'polls/js/jquery.prettyPhoto.js' %}"></script>
    <script type="text/javascript" src="{% static 'polls/js/scripts.js' %}"></script>
    <script type="text/javascript" src="{% static 'polls/js/Chart.js' %}"></script>
    
</head>
<body>
<div id="body-wrapper">
    <!-- Begin Header -->
    <div id="header">
        <div class="logo">
            <a href="index.html"><img src="{% static 'polls/images/logo.png' %}" alt=""/></a>
        </div>


        <!-- Begin Menu -->
        <div class="menu">

            <ul class="sf-menu">
                <li><a href="/polls/">Home</a></li>
                <li><a href="/polls/create">Create a Poll</a></li>
                <li><a href="/polls/directory">Directory</a></li>
                <li><a href="/polls/search">Search</a></li>
                {% if logged_in %}
                    <li><a href="{% url 'polls:account' %}">My Account</a></li>
                    <li><a href="{% url 'polls:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'polls:register' %}">Register</a></li>
                {% endif %}


            </ul>

        </div>
        <div class="clear"></div>
        <!-- End Menu -->

    </div>
    <!-- End Header -->


    <!-- Begin Wrapper -->
    <div id="wrapper">

        {% block content %}


        {% endblock content %}


        <div class="sidebar">

            <div class="sidebox">
                <h3 class="line">About</h3>

                <p>Welcome to PollNation the #1 place on the web to create and vote on polls!</p>
                <br/>

                <p>Built with Django! </p>
            </div>

    {% if auth_form %}
        <div class="sidebox">
        <div class="form-container">
            <form class="forms" action="/polls/login" method="post">
                <fieldset>
                    <ol>
                        {% csrf_token %}
                        {% for field in auth_form %}
                            <li class="form-row text-input-row">{{ field }}</li>
                        {% endfor %}
                    </ol>
                    <input type="submit" id="btnLogIn" value="Log In">
                </fieldset>
            </form>
        </div></div>
    {% endif %}


{% block sidebar %}
        {% endblock sidebar %}
    <div class="sidebox">
        <h3 class="line">Popular Polls</h3>
        <ul class="popular-posts">
            {% for p in top_polls %}
                <li>

                    <h5><a href="{% url 'polls:detail' p.id %}">{{ p.question }}</a></h5>
                    <span>{{ p.pub_date }} | <a href="{% url 'polls:detail' p.id %}">{{ p.num_votes }} Votes</a> | <a
                            href="{% url 'polls:detail' p.id %}">{{ p.comment_set.count }} Comments</a></span>
                </li>
            {% endfor %}
        </ul>
    </div>


    <div class="sidebox">
        <h3 class="line">Top Tags</h3>
        <ul class="cat-list">
            {% for tag in top_tags %}
                <li><a href="/polls/search?q={{ tag }}">{{ tag }} ({{ tag.num_times }})</a></li>

            {% endfor %}
        </ul>
    </div>



        <div class="sidebox">
                    <h3 class="line">Search</h3>

                    <form class="searchform" action="{% url 'polls:search' %}" method="get">
                        <input type="text" id="id_q" name="q" value="type and hit enter" onfocus="this.value=''"
                               onblur="this.value='type and hit enter'"/>
                    </form>
                </div>
        </div>
        <div class="clear"></div>

    </div>
    <!-- End Wrapper -->

    <div class="push"></div>
</div>
<!-- End Body Wrapper -->

<div id="footer">
    <div class="footer">
        <p>Copyright &copy; 2013 PollNation. All Rights Reserved.</p>
    </div>
</div>

</body>
</html>

polls/templates/polls/create.html
{% extends "polls/base.html" %}

{% block content %}
    
    <div class="intro">Create Your Own Poll!</div>

    <!-- Begin Container -->
    <div class="container">
        {% if poll_form.non_field_errors %}
            <div class="flash error">

                {{ poll_form.non_field_errors }}
            </div>
        {% endif %}


        <div class="form-container">
            <form class="forms" action="{% url 'polls:create' %}" method="POST">
                <fieldset>
                {% csrf_token %}

        {{ poll_form.as_p }}

    <h2>Poll Choices</h2>
    {{ choice_formset.management_form }}
    {% for form in choice_formset.forms %}

      <div class="item">
      {{ form.as_p }}
      <p style=""><a class="button red delete" href="#">Delete</a></p>
    </div>



    {% endfor %}
    <p><a class="button green" id="add" href="#">Add another item</a></p>
    <input type="submit" value=" Submit " />
                </fieldset>
</form>
        </div>
    </div>

    

{% endblock content %}

polls/templates/polls/delete.html
{% extends 'polls/base.html' %}

{% block content %}
    <div class="intro">{{ poll.question }}</div>

    <!-- Begin Blog -->
    <div class="container">
        <div class="post photo">
            <div class="icon-chat"></div>
            <div class="content">
                <div class="top"></div>
                <div class="middle">
                 <div class="post-text">
                    <h2 class="title"><a href="{% url 'polls:detail' poll.id %}">Delete Poll "{{ poll.question }}"</a></h2>

                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

                        <form action="{% url 'polls:delete' poll.id %}" method="post">
                            {% csrf_token %}

                            <input type="hidden" name="id" value="{{ poll.id }}" />
                            <input type="submit" value="Confirm Delete"/>
                        </form>
                    </div>
                    <div class="meta-wrapper">
                        <div class="meta">
                            <ul class="post-info">
                                <li><span class="post-link"></span><a href="#">{{ poll.pub_date }}</a></li>
                                <li><span class="post-comment"></span><a href="#">{{ poll.comment_set.count }} Comments</a></li>
                                <li><span class="post-tag"></span>{% for tag in poll.tags.all %}
                                    <a href="#">{{ tag }}</a>,
                                {% endfor %}</li>
                            </ul>
                            <div class="share"><span class="post-share"></span><a href="#">Share</a></div>
                            <div class="clear"></div>
                        </div>
                    </div>
                </div>
                <div class="bottom"></div>
            </div>
        </div>

</div>
{% endblock content %}

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
    <div class="intro">{{ poll.question }}</div>

    <!-- Begin Blog -->
    <div class="container">
        <div class="post photo">
            <div class="icon-chat"></div>
            <div class="content">
                <div class="top"></div>
                <div class="middle">
                    
                         <div id="pie{{ poll.id }}"
                         style="padding-top: 20px; margin-left: 20px; width: 495px; height: 347px; position: relative;"
                         class="jqplot-target"></div>
                    <script>
                        $(document).ready(function () {
                            var plot{{ poll.id }} = $.jqplot('pie{{ poll.id }}', [
                                [

                                    {% for choice in poll.choice_set.all %}

                                        ['{{ choice.choice_text }} - {{choice.votes}}', {{choice.votes}}],

                                    {% endfor %}
                                ]
                            ], {
                                
                                seriesColors: [ "#ffc100", "#4bb2c5", "#ff6c00", "#52f6a1", "#b5ff00", "#0085cc",
                                                "#f526b9", "#4b5de4", "#ff0000", "#00eaff", "#ffed00"],

                                seriesDefaults: {
                                    renderer: $.jqplot.PieRenderer,
                                    trendline: { show: false },
                                    rendererOptions: { padding: 10, showDataLabels: true }
                                },
                                legend: { show: true, location: 'e' }
                            });
                        });
                    </script>
                   
                    <div class="post-text">
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

                        <form action="{% url 'polls:vote' poll.id %}" method="post">
                            {% csrf_token %}
                            {% for choice in poll.choice_set.all %}
                                <input type="radio" name="choice" id="choice{{ forloop.counter }}"
                                       value="{{ choice.id }}"/>
                                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
                            {% endfor %}
                            <input type="submit" value="Vote"/>
                        </form>
                    </div>
                    <div class="meta-wrapper">
                        <div class="meta">
                            <ul class="post-info">
                                <li><span class="post-link">Created: </span><a href="#">{{ poll.pub_date }}</a></li>
                                <li><span class="post-comment"></span><a href="#">{{ poll.comment_set.count }} Comment{{ poll.comment_set.count|pluralize }}</a></li>
                                <li><span class="post-tag"></span>{% for tag in poll.tags.all %}
                                    <a href="#">{{ tag }}</a>,
                                {% endfor %}</li>
                            </ul>
                            <div class="share"><span class="post-share"></span><a href="#">Share</a></div>
                            <div class="clear"></div>
                        </div>
                    </div>
                </div>
                <div class="bottom"></div>
            </div>
        </div>


        <!-- Begin Comments Section -->
        <!-- Begin Comments -->
        {% if poll.comment_set.count > 0 %}
            <h3 class="line">{{ poll.comment_set.count }} Response{{ poll.comment_set.count|pluralize }}</h3>

            <!-- Begin Comments -->
            <div id="comments">
                <ol id="singlecomments" class="commentlist">
                    {% for comment in poll.comment_set.all %}
                        <li class="clearfix">
                            <div class="user"><img alt="" src="{{ comment.user.profile.gravatar_url }}" height="48"
                                                   width="48" class="avatar"/></div>
                            <div class="message">
                                <div class="info">
                                    <h4><a href="#">{{ comment.user.username }}</a></h4>
                                    <span class="date">{{ comment.comment_date }}</span></div>
                                <p>{{ comment.comment_text }}</p>
                            </div>
                            <div class="clear"></div>
                        </li>
                    {% endfor %}
                </ol>
            </div>
        {% endif %}
        <!-- End Comments -->
{% if logged_in %}
        <!-- Begin Form -->
        <div class="comment-form">
            <h3 class="line">Leave a Reply</h3>


                       <div class="form-container">
            <form class="forms" action="{% url 'polls:comment' %}" method="post">
                <fieldset>
                    <ol>
                        {% csrf_token %}
                        {% for field in comment_form %}
                            <li class="form-row text-area-row"><label>{{ field.label|title }}:</label>{{ field }}</li>
                        {% endfor %}
                    </ol>
                    <input type="hidden" name="pollid" value="{{ poll.id }}" />
                    <input type="submit" value="Submit Comment">
                </fieldset>


            </form>

                    </fieldset>
                </form>
                <div class="response"></div>
            </div>
        </div>
        <!-- End Form -->
        {% else %}
        <h3 class="line">Sign In or Sign Up to Leave a Comment</h3>
        {% endif %}

        <!-- End Comments -->
        <!-- End Comments Section -->

    </div>
    <!-- End Container -->
{% endblock content %}

{% block sidebar %}
    {% if similar_polls.count > 0 %}
    <div class="sidebox">
        <h3 class="line">Similar Polls</h3>
        <ul class="popular-posts">
            {% for p in similar_polls %}
                <li>

                    <h5><a href="{% url 'polls:detail' p.id %}">{{ p.question }}</a></h5>
                    <span>{{ p.pub_date }} | <a href="{% url 'polls:detail' p.id %}">{{ p.num_votes }} Votes</a> | <a
                            href="{% url 'polls:detail' p.id %}">{{ p.comment_set.count }} Comment{{ p.comment_set.count|pluralize }}</a></span>
                </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
        {% endblock sidebar %}